name: npm-test
on:
  push:
    branches: "main"
    paths:
      - src/*/**
      - .github/workflows/npm-test.yml
  pull_request:
    paths:
      - src/*/**
      - .github/workflows/npm-test.yml
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  npm-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-actions/setup-vcpkg@v1
      - uses: cpp-actions/setup-clang-format@v1
      - uses: cpp-actions/setup-doxygen@v1
      - run: pip install cmake-format
      - run: pip install conan
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: npm
      - run: npm ci
      - run: npm test
